CREATE TABLE PRODUCTS(
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    PRODUCT_NAME TEXT NOT NULL,
    PRODUCT_MANUFACTURER TEXT NOT NULL,
    WARRANTY BOOLEAN NOT NULL,
    PRODUCT_MANUFACTURING_DATE DATE NOT NULL
);