INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('GLC 220d', 'Mercedes', true, '2023-06-06');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('GLE 350d', 'Mercedes', true, '2018-12-19');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('Galaxy S20', 'Samsung', false, '2020-03-20');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('Redmi 6', 'Xiaomi', false, '2015-07-20');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('WGG142Z0BY Masina za pranje vesa', 'BOSCH', true, '2024-10-10');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('IDEAPAD 1', 'Lenovo', false, '2021-07-15');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('X5', 'BMW', true, '2017-09-12');
INSERT INTO products(PRODUCT_NAME, PRODUCT_MANUFACTURER, WARRANTY, PRODUCT_MANUFACTURING_DATE) VALUES ('M3', 'BMW', true, '2010-10-21');